# Generated by Django 3.1.3 on 2020-11-08 18:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(upload_to=api.models.company_directory_path, verbose_name='Company logo')),
                ('base_price', models.FloatField(verbose_name='Base price')),
                ('min_price', models.FloatField(verbose_name='Min price')),
                ('max_price', models.FloatField(verbose_name='Max price')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
