# Generated by Django 3.1.3 on 2020-11-08 20:49

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DRIVER'), (2, 'BUSINESS')], default=1, editable=False, verbose_name='User type'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(upload_to=api.models.company_directory_path, verbose_name='Company logo')),
                ('base_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base price')),
                ('min_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min price')),
                ('max_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max price')),
                ('percent_over_speeding', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent allowed over speeding')),
                ('min_speed_commit_rotate_head', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Minimum speed to commit rotate head')),
                ('percent_head_rotate_for_hour', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent head rotation for hour')),
                ('max_speed_discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max speed discount')),
                ('max_speed_penalty', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max speed penalty')),
                ('max_rotate_head_discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max rotate head discount')),
                ('max_rotate_head_penalty', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max rotate head penalty')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(min_price__lte=django.db.models.expressions.F('base_price')), name='Min price must be <= base price.'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(max_price__gte=django.db.models.expressions.F('base_price')), name='Max price must be >= base price.'),
        ),
    ]
