# Generated by Django 3.1.3 on 2020-11-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='month',
            new_name='months',
        ),
    ]
