export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const IS_LOADING = "IS_LOADING";
export const END_LOADING = "END_LOADING";
export const REFRESH_SENSORS = "REFRESH_SENSORS";

export const LOADING_COMPANIES = "LOADING_COMPANIES";
export const REFRESH_COMPANIES = "REFRESH_COMPANIES";
export const COMPANIES_LOADED = "COMPANIES_LOADED";
